name: Pull request workflow
on:
  pull_request:

jobs:
  backend-checks:
    name: Backend checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install --frozen-lockfile

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx lint backend
      - run: npx nx test backend

  webapp-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: yarn install --frozen-lockfile
      - run: npx nx format:check
      - run: npx nx lint webapp
      - run: npx nx test webapp

  webapp-deploy:
    runs-on: ubuntu-latest
    needs: [webapp-checks]
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    environment:
      name: Firebase
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn nx build webapp
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FEATHER_22710 }}'
          projectId: feather-22710
